### ISSUE TITLE
Bug: page numbers don't always show on hover

### ISSUE THREAD

**Issue by kuoirene** [amosproj/amos2024ss05-knowledge-graph-extractor#188]
**Describe the bug**
After a knowledge graph is generated, sometimes the page numbers aren't showing on hover and instead it says "no page in metadata". However, as it is a document type that should have page numbers, this should not be the case
![Image](https://github.com/amosproj/amos2024ss05-knowledge-graph-extractor/assets/5893774/73577794-f279-4071-a3d3-72bb2f14d6e5)

**To Reproduce**
1. Upload of this document has so far consistently resulted in failure. 

[AMOS B01 - Team and Tools.pptx](https://github.com/user-attachments/files/16131183/AMOS.B01.-.Team.and.Tools.pptx)

**Expected behavior**
For document types of .docx, .pdf, .pptx where there are page numbers available, the page numbers should always be included in the metadata and thus show on hover over an entity.

**Comment by kristikotini** [comment]
@kuoirene I tried for .docx files to find a way to read the page numbers but it seems there is not straightforward and reliable way. The package does not support it. Also from a quick search it seems that this is on purpose since like I mentioned there is not way to do that for these docs since it depends on the render engine and most of the time pages are found based on the line breaks. 

For .pptx files the package allowed it and it is fixed in the [PR](https://github.com/amosproj/amos2024ss05-knowledge-graph-extractor/pull/201).
